services:
  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    ports:
      - '80:80'
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: apps/server/Dockerfile
    environment:
      - DATABASE_URL=postgresql://mg_user:mg_password@postgres:5432/migrationguard_prod?schema=public
      - AWS_ENDPOINT=http://minio:9000
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=admin123
      - S3_BUCKET=migrationguard-prod
      - JWT_SECRET=production_super_secret_key_123!
      - FRONTEND_ORIGIN=*
    depends_on:
      - postgres
      - minio
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=mg_user
      - POSTGRES_PASSWORD=mg_password
      - POSTGRES_DB=migrationguard_prod
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=admin123
    volumes:
      - miniodata:/data
    ports:
      - '127.0.0.1:9002:9000'
    restart: unless-stopped

volumes:
  pgdata:
  miniodata:
